//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class MyPanel extends JPanel {
    private JLabel jcomp1;
    private JLabel jcomp2;
    private JLabel jcomp3;

    public MyPanel() {
        //construct components
        jcomp1 = new JLabel ("Usted ha ingresado lo siguiente:");
        jcomp2 = new JLabel ("Emoción: Felicidad");
        jcomp3 = new JLabel ("Entorno: Universidad");

        //adjust size and set layout
        setPreferredSize (new Dimension (338, 213));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (75, 35, 200, 30);
        jcomp2.setBounds (110, 75, 120, 25);
        jcomp3.setBounds (105, 105, 145, 30);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("MyPanel");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new MyPanel());
        frame.pack();
        frame.setVisible (true);
    }
}
